const jsonData = [
    {
      "WOMEMNACOUNT" : 0,
      "MENACOUNT" : 1,
      "ID_DEPARTAMENT" : 4,
      "DEPARTAMENT" : "02 - Colón",
      "ID_TOWN" : 9,
      "TOWN" : "01 - Trujillo",
      "INSCRIPTIONTYPE" : "NACIMIENTOS",
      "INSCRIPTION_ID" : 1,
      "DESCRIPTION" : "Normal",
      "USERGENERATED" : "user_rnp",
      "INSCRIPTIONDATE" : "1969-07-13T05:00:00.000Z"
    },
    {
      "WOMEMNACOUNT" : 1,
      "MENACOUNT" : 0,
      "ID_DEPARTAMENT" : 3,
      "DEPARTAMENT" : "01 - Atlántida",
      "ID_TOWN" : 5,
      "TOWN" : "09 - La Ceiba",
      "INSCRIPTIONTYPE" : "NACIMIENTOS",
      "INSCRIPTION_ID" : 1,
      "DESCRIPTION" : "Normal",
      "USERGENERATED" : "user_rnp",
      "INSCRIPTIONDATE" : "2003-07-31T05:00:00.000Z"
    },
    {
      "WOMEMNACOUNT" : 1,
      "MENACOUNT" : 1,
      "ID_DEPARTAMENT" : 3,
      "DEPARTAMENT" : "01 - Atlántida",
      "ID_TOWN" : 5,
      "TOWN" : "09 - La Ceiba",
      "INSCRIPTIONTYPE" : "NACIMIENTOS",
      "INSCRIPTION_ID" : 1,
      "DESCRIPTION" : "Normal",
      "USERGENERATED" : "administrador",
      "INSCRIPTIONDATE" : "2023-07-10T05:00:00.000Z"
    },
    {
      "WOMEMNACOUNT" : 0,
      "MENACOUNT" : 1,
      "ID_DEPARTAMENT" : 3,
      "DEPARTAMENT" : "01 - Atlántida",
      "ID_TOWN" : 5,
      "TOWN" : "09 - La Ceiba",
      "INSCRIPTIONTYPE" : "NACIMIENTOS",
      "INSCRIPTION_ID" : 1,
      "DESCRIPTION" : "Normal",
      "USERGENERATED" : "user_rnp",
      "INSCRIPTIONDATE" : "2023-06-06T05:00:00.000Z"
    },
    {
      "WOMEMNACOUNT" : 0,
      "MENACOUNT" : 1,
      "ID_DEPARTAMENT" : 3,
      "DEPARTAMENT" : "01 - Atlántida",
      "ID_TOWN" : 5,
      "TOWN" : "09 - La Ceiba",
      "INSCRIPTIONTYPE" : "NACIMIENTOS",
      "INSCRIPTION_ID" : 1,
      "DESCRIPTION" : "Normal",
      "USERGENERATED" : "administrador",
      "INSCRIPTIONDATE" : "2023-07-11T05:00:00.000Z"
    },
    {
      "WOMEMNACOUNT" : 1,
      "MENACOUNT" : 0,
      "ID_DEPARTAMENT" : 3,
      "DEPARTAMENT" : "01 - Atlántida",
      "ID_TOWN" : 5,
      "TOWN" : "09 - La Ceiba",
      "INSCRIPTIONTYPE" : "NACIMIENTOS",
      "INSCRIPTION_ID" : 2,
      "DESCRIPTION" : "Reinscripción",
      "USERGENERATED" : "user_rnp",
      "INSCRIPTIONDATE" : "2023-06-06T05:00:00.000Z"
    },
    {
      "WOMEMNACOUNT" : 1,
      "MENACOUNT" : 0,
      "ID_DEPARTAMENT" : 4,
      "DEPARTAMENT" : "02 - Colón",
      "ID_TOWN" : 9,
      "TOWN" : "01 - Trujillo",
      "INSCRIPTIONTYPE" : "NACIMIENTOS",
      "INSCRIPTION_ID" : 1,
      "DESCRIPTION" : "Normal",
      "USERGENERATED" : "user_rnp",
      "INSCRIPTIONDATE" : "2023-06-29T05:00:00.000Z"
    },
    {
      "WOMEMNACOUNT" : 0,
      "MENACOUNT" : 1,
      "ID_DEPARTAMENT" : 1,
      "DEPARTAMENT" : "05 - Antioquia",
      "ID_TOWN" : 1,
      "TOWN" : "01 - Medellin",
      "INSCRIPTIONTYPE" : "NACIMIENTOS",
      "INSCRIPTION_ID" : 1,
      "DESCRIPTION" : "Normal",
      "USERGENERATED" : "user_rnp",
      "INSCRIPTIONDATE" : "2024-06-15T05:00:00.000Z"
    },
    {
      "WOMEMNACOUNT" : 0,
      "MENACOUNT" : 1,
      "ID_DEPARTAMENT" : 3,
      "DEPARTAMENT" : "01 - Atlántida",
      "ID_TOWN" : 5,
      "TOWN" : "09 - La Ceiba",
      "INSCRIPTIONTYPE" : "NACIMIENTOS",
      "INSCRIPTION_ID" : 1,
      "DESCRIPTION" : "Normal",
      "USERGENERATED" : "user_rnp",
      "INSCRIPTIONDATE" : "2023-07-04T05:00:00.000Z"
    },
    {
      "WOMEMNACOUNT" : 0,
      "MENACOUNT" : 1,
      "ID_DEPARTAMENT" : 3,
      "DEPARTAMENT" : "01 - Atlántida",
      "ID_TOWN" : 5,
      "TOWN" : "09 - La Ceiba",
      "INSCRIPTIONTYPE" : "NACIMIENTOS",
      "INSCRIPTION_ID" : 1,
      "DESCRIPTION" : "Normal",
      "USERGENERATED" : "user_rnp",
      "INSCRIPTIONDATE" : "2000-01-01T05:00:00.000Z"
    },
    {
      "WOMEMNACOUNT" : 0,
      "MENACOUNT" : 1,
      "ID_DEPARTAMENT" : 4,
      "DEPARTAMENT" : "02 - Colón",
      "ID_TOWN" : 9,
      "TOWN" : "01 - Trujillo",
      "INSCRIPTIONTYPE" : "NACIMIENTOS",
      "INSCRIPTION_ID" : 1,
      "DESCRIPTION" : "Normal",
      "USERGENERATED" : "user_rnp",
      "INSCRIPTIONDATE" : "1971-09-12T05:00:00.000Z"
    }
  ]
  export default jsonData;